[tool.poetry]
name = "flask-blipp"
version = "0.1.0"
description = ""
authors = ["colinlcrawford <ccolin84@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
flask = "^2.2"
black = {version = "^23.3", allows-prereleases = true}
pycodestyle = "^2.10"
pytest-cov = "^4.0"
coveralls = "^3.3"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
