[tool.poetry]
name = "flask-blipp"
version = "0.1.0"
description = ""
authors = ["colinlcrawford <ccolin84@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
flask = "^2.0"
black = {version = "^21.9b0", allows-prereleases = true}
pycodestyle = "^2.7"
pytest-cov = "^3.0"
coveralls = "^3.2"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
