[tool.poetry]
name = "flask-blipp"
version = "0.1.0"
description = ""
authors = ["colinlcrawford <ccolin84@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
flask = "^1.1"
black = {version = "^19.10b0", allows-prereleases = true}
pycodestyle = "^2.6"
pytest-cov = "^2.10"
coveralls = "^2.1"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
